#!/usr/bin/env node
'use strict';

/**
 * 构建云函数**单文件**部署产物
 *
 * ═══════════ 为什么必须打包成单文件（2026-09-28 实证定案）═══════════
 * 微信开发者工具 CLI 在 Windows 上打包「云函数目录」时，会把路径分隔符 `\`
 * 原样写进压缩包的条目名。云端（Linux）解压后得到的是**一堆「文件名里带 `\` 的扁平文件」**：
 *
 *     /var/user/lib\response.js       ← 这是一个「文件」，不是 lib 目录下的 response.js
 *     /var/user/lib                   ← 空目录（ENOENT 语义）
 *
 * → `require('./lib/response')` 必然失败。
 *
 * ⚠️⚠️ 实测结论（**推翻了早期记录**）：
 *   · `deploy`         → 子目录文件全部带 `\`，坏
 *   · `inc-deploy --file <目录>` → 同样坏（连 handlers/user 这种二级目录更坏）
 *   · `inc-deploy --file <单文件>` → **也坏**（条目名仍是 `handlers\index.js`）
 *   · 只有**根目录下的文件**（index.js / router.js / config.js / package.json）传得正确
 *   · 阶段 3 之所以“成功过”，是因为那次是**在开发者工具 GUI 里点的上传**，不是 CLI
 *
 * ✅ 所以正解：**把整个云函数打成单文件 index.js**，部署时只传根文件 —— 彻底绕开该缺陷，
 *    也不再需要人工点 GUI，全流程可脚本化。
 *
 * ═══════════ 打包器实现（零依赖，不引 esbuild）═══════════
 * 我们的模块很规整：CommonJS + **字面量 require 路径**（含 handlers/index.js 里的
 * `() => require('./user/auth')` 写法）。因此：
 *   · 用正则扫出所有 `require('...')`，相对路径递归收集进包；
 *   · **不改写源码**，而是给每个模块注入一个 `__makeRequire(fromId)`：
 *     相对路径走包内注册表，其他（wx-server-sdk / axios / bcryptjs / jsonwebtoken / fs / path…）
 *     直接交给原生 require。
 *   · 入口是 index.js，产物末尾导出它的 exports。
 *
 * ⚠️ 新增模块**不需要**在这里登记 —— 只要 require 路径是字符串字面量就会自动被收进来。
 *    （这也是 handlers/index.js 必须用 `() => require('./user/auth')` 而不能动态拼路径的原因。）
 *
 * 用法：
 *   node cloud/scripts/sync.js           # 构建产物
 *   node cloud/scripts/sync.js --check   # 只校验产物是否最新（自检用）
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const SRC = path.join(ROOT, 'cloud', 'cloudfunctions', 'api');
const DST = path.join(ROOT, 'miniprogram', 'cloudfunctions', 'api');
const ENTRY = 'index.js';
const OUT_NAME = 'index.js';
const BANNER = '/* eslint-disable */\n/* AUTO-GENERATED by cloud/scripts/sync.js —— 请勿手改；改源码后重跑本脚本 */';

/** 不以 `.` 开头 → 外部依赖（交给原生 require） */
const isExternal = (spec) => spec.charAt(0) !== '.';

/** 把 `require('./x')` 的 spec 解析成包内模块 id（相对 SRC 的 posix 路径） */
function resolveId(fromId, spec) {
  const dir = path.posix.dirname(fromId);
  const joined = path.posix.join(dir, spec);
  // ⚠️ 必须排除**目录**：`require('./handlers')` 的无扩展名候选 'handlers' 恰好是个目录，
  //    existsSync 会为 true，于是把目录名当模块 id → readFileSync 报 EISDIR。
  const candidates = [joined, `${joined}.js`, `${joined}/index.js`, `${joined}.json`];
  for (const c of candidates) {
    try {
      if (fs.statSync(path.join(SRC, c)).isFile()) return c;
    } catch (e) { /* 候选不存在，继续 */ }
  }
  return null;
}

/** 从入口递归收集模块（id -> 源码） */
function collect(entryId, out = new Map()) {
  if (out.has(entryId)) return out;
  const abs = path.join(SRC, entryId);
  const code = fs.readFileSync(abs, 'utf8');
  out.set(entryId, code);

  const re = /require\(\s*(['"])([^'"]+)\1\s*\)/g;
  let m;
  while ((m = re.exec(code))) {
    const spec = m[2];
    if (isExternal(spec)) continue;
    const id = resolveId(entryId, spec);
    if (!id) {
      // 注释里的示例 require 会走到这里 —— 保留原样，不报错
      continue;
    }
    collect(id, out);
  }
  return out;
}

const RUNTIME = `
// ───── 包内模块系统（等价 Node 的 require 语义，含循环依赖与缓存）─────
var __mods = {};
var __cache = {};
var __nativeRequire = require;

function __resolve(fromId, spec) {
  var stack = fromId.split('/');
  stack.pop(); // 去掉文件名，留下目录
  spec.split('/').forEach(function (seg) {
    if (seg === '' || seg === '.') return;
    if (seg === '..') stack.pop();
    else stack.push(seg);
  });
  return stack.join('/');
}

function __load(id) {
  if (__cache[id]) return __cache[id].exports;
  var m = { exports: {} };
  __cache[id] = m;                       // 先登记再执行 —— 与 Node 一致，允许循环依赖
  __mods[id].call(m.exports, m, m.exports, __makeRequire(id));
  return m.exports;
}

function __makeRequire(fromId) {
  return function (spec) {
    if (spec.charAt(0) !== '.') return __nativeRequire(spec);
    // ⚠️ 候选必须各自基于 base 拼接。曾写成「依次改写同一个 id 变量」，
    //    于是 './handlers' 会变成 'handlers' → 'handlers.js' → 'handlers.js/index.js'，永远命中不了。
    var base = __resolve(fromId, spec);
    if (__mods[base]) return __load(base);
    if (__mods[base + '.js']) return __load(base + '.js');
    if (__mods[base + '/index.js']) return __load(base + '/index.js');
    throw new Error("Cannot find module '" + spec + "' from '" + fromId + "'");
  };
}
// ─────────────────────────────────────────────────────────────
`;

function build() {
  const mods = collect(ENTRY);
  const parts = [BANNER, RUNTIME];

  // 入口最后登记没有意义，顺序不影响正确性（惰性加载）
  mods.forEach((code, id) => {
    parts.push(`__mods[${JSON.stringify(id)}] = function (module, exports, require) {`);
    parts.push(code);
    parts.push('};');
  });

  parts.push(`module.exports = __load(${JSON.stringify(ENTRY)});`);
  return { text: parts.join('\n'), count: mods.size };
}

/** 清空目标目录（避免旧的镜像文件被一起上传） */
function cleanDir(dir) {
  if (!fs.existsSync(dir)) return;
  fs.readdirSync(dir).forEach((name) => {
    fs.rmSync(path.join(dir, name), { recursive: true, force: true });
  });
}

function run(checkOnly) {
  const { text, count } = build();
  const outFile = path.join(DST, OUT_NAME);

  if (checkOnly) {
    const bannerOk = fs.existsSync(outFile)
      && fs.readFileSync(outFile, 'utf8').indexOf('AUTO-GENERATED by cloud/scripts/sync.js') >= 0;
    if (!bannerOk) {
      console.log('[build:check] 部署产物缺失或不是打包产物 → 修复：node cloud/scripts/sync.js');
      process.exit(1);
    }
    console.log(`[build:check] 产物存在（${(fs.statSync(outFile).size / 1024).toFixed(1)} KB）`);
    return;
  }

  fs.mkdirSync(DST, { recursive: true });
  cleanDir(DST);

  // package.json 仍要单独带上（云端靠它装依赖）
  fs.copyFileSync(path.join(SRC, 'package.json'), path.join(DST, 'package.json'));
  fs.writeFileSync(outFile, text, 'utf8');

  /**
   * config.json（云函数触发器配置，阶段 6）—— 必须**原样复制**到产物目录。
   *
   * ⚠️⚠️ 这个文件是**平台侧解析**的：它决定定时触发器是否存在。
   *    漏传的表现是「函数部署成功、日志一片正常、但定时任务从来不跑」——
   *    纯静默，排查代价极高。所以：
   *      ① 必须跟着 index.js 一起上传（`deploy --names api -r` 传的是整个目录）；
   *      ② `cleanDir()` 会清空产物目录，所以只能在这里复制，不能手动往里放。
   * 内容：triggers[0] = { name: songSweepTick, type: timer, config: 每分钟第 0 秒 }
   *      —— 微信云开发小程序端**只支持一个触发器**；cron 为 **7 位**
   *      「秒 分 时 日 月 周 年」，写法见源文件 `cloud/cloudfunctions/api/config.json`。
   *      （⚠️ 这一段刻意不把 cron 字面量抄进来：`*` + `/` 会提前闭合本块注释。）
   */
  const cfgSrc = path.join(SRC, 'config.json');
  if (fs.existsSync(cfgSrc)) {
    const cfgText = fs.readFileSync(cfgSrc, 'utf8');
    try {
      const parsed = JSON.parse(cfgText);
      if (!parsed || !Array.isArray(parsed.triggers) || !parsed.triggers.length) {
        throw new Error('triggers 缺失或为空');
      }
      parsed.triggers.forEach((t) => {
        if (!t || t.type !== 'timer' || !t.name || !t.config) {
          throw new Error(`触发器字段不全：${JSON.stringify(t)}`);
        }
        if (String(t.config).split(/\s+/).filter(Boolean).length !== 7) {
          throw new Error(`cron 必须是 7 位（秒 分 时 日 月 周 年）：${t.config}`);
        }
      });
    } catch (e) {
      // 宁可让构建失败，也不要静默传一个「触发器永远不生效」的配置上去
      console.error(`[build] config.json 非法 → 中止：${e.message}`);
      process.exit(1);
    }
    fs.copyFileSync(cfgSrc, path.join(DST, 'config.json'));
  }

  const kb = (Buffer.byteLength(text) / 1024).toFixed(1);
  console.log(`[build] 已打包 ${count} 个模块 → miniprogram/cloudfunctions/${'api'}/${OUT_NAME}（${kb} KB）`);
  if (fs.existsSync(path.join(DST, 'config.json'))) {
    console.log('[build] 已带上 config.json（定时触发器，每分钟第 0 秒 → sweepTick）');
  }
  console.log('[build] 部署只需传根文件：deploy --names api ... -r（**不要**再 inc-deploy 子目录）');
}

fs.mkdirSync(DST, { recursive: true });
run(process.argv.includes('--check'));
